using HONIFS.Leads;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace HONIFS.Leads
{
    public class Lead : LeadBase
    {
        //<suite-custom-code-autogenerated>
        protected Lead()
        {

        }

        public Lead(Guid id, string firstName, string lastName, string userName, string email, string contact, string tenantName, LeadType type, string? address = null)
            : base(id, firstName, lastName, userName, email, contact, tenantName, type, address)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}