using HONIFS.Leads;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HONIFS.Leads
{
    public class LeadManager : LeadManagerBase
    {
        //<suite-custom-code-autogenerated>
        public LeadManager(ILeadRepository leadRepository)
            : base(leadRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}