using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HONIFS.Permissions;
using HONIFS.Leads;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HONIFS.Shared;

namespace HONIFS.Leads
{
    public class LeadsAppService : LeadsAppServiceBase, ILeadsAppService
    {
        //<suite-custom-code-autogenerated>
        public LeadsAppService(ILeadRepository leadRepository, LeadManager leadManager, IDistributedCache<LeadDownloadTokenCacheItem, string> downloadTokenCache)
            : base(leadRepository, leadManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}